/****************************************************************************
 * Pharos - A Real-Time Secure Operating System                             *
 * Copyright 2020 Pedro Macara and Filipe Monteiro                          *
 *                                                                          *
 * Licensed under the Apache License, Version 2.0 (the "License");          *
 * you may not use this file except in compliance with the License.         *
 * You may obtain a copy of the License at                                  *
 *                                                                          *
 *     http://www.apache.org/licenses/LICENSE-2.0                           *
 *                                                                          *
 * Unless required by applicable law or agreed to in writing, software      *
 * distributed under the License is distributed on an "AS IS" BASIS,        *
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. *
 * See the License for the specific language governing permissions and      *
 * limitations under the License.                                           *
 *                                                                          *
 ****************************************************************************/


#ifndef PHAROS_RISC64_ASM_H
#define	PHAROS_RISC64_ASM_H

#include <pharos/hal/def.h>


#define PHAROS_CPU_MCAUSE_INTERRUPT_BIT         (1UL << 63U)

#define PHAROS_CPU_MCAUSE_MTIMER_INTERRUPT      (3U)
#define PHAROS_CPU_MCAUSE_MEXTERNAL_INTERRUPT   (11U)

#define PHAROS_CPU_MSTATUS_MIE_BIT              (3U)
#define PHAROS_CPU_MSTATUS_MPIE_BIT             (7U)
#define PHAROS_CPU_MSTATUS_MIE_DIS              (0 << 3U)
#define PHAROS_CPU_MSTATUS_MIE                  (1U << 3U)
#define PHAROS_CPU_MSTATUS_UIE                  (1U << 0U)
#define PHAROS_CPU_MSTATUS_SIE                  (1U << 1U)
#define PHAROS_CPU_MSTATUS_UPIE                 (1U << 4U)
#define PHAROS_CPU_MSTATUS_SPIE                 (1U << 5U)
#define PHAROS_CPU_MSTATUS_MPIE                 (1U << 7U)
#define PHAROS_CPU_MSTATUS_MPP_USER             (0U << PHAROS_CPU_MSTATUS_MPP_BIT)
#define PHAROS_CPU_MSTATUS_MPP_BIT              (11U)
#define PHAROS_CPU_MSTATUS_MPP_MASK             (3U << 11U)
#define PHAROS_CPU_MSTATUS_MPP_MACHINE          (3U << PHAROS_CPU_MSTATUS_MPP_BIT)
#define PHAROS_CPU_MSTATUS_FS_BIT               (13U)
#define PHAROS_CPU_MSTATUS_FS_MASK              (3U << PHAROS_CPU_MSTATUS_FS_BIT)
#define PHAROS_CPU_MSTATUS_XS_BIT               (15U)
#define PHAROS_CPU_MSTATUS_XS_MASK              (3U << PHAROS_CPU_MSTATUS_XS_BIT)

#define PHAROS_CPU_MIE_USIE                     (1U << 0)
#define PHAROS_CPU_MIE_SSIE                     (1U << 1)
#define PHAROS_CPU_MIE_MSIE                     (1U << 3)

#define PHAROS_CPU_MIE_UTIE                     (1U << 4U)
#define PHAROS_CPU_MIE_STIE                     (1U << 5U)
#define PHAROS_CPU_MIE_MTIE                     (1U << 7U)

#define PHAROS_CPU_MIE_UEIE                     (1U << 8U)
#define PHAROS_CPU_MIE_SEIE                     (1U << 9U)
#define PHAROS_CPU_MIE_MEIE                     (1U << 11U)

#define PHAROS_CPU_MIP_MSIP_BIT                 (3U)

#define PHAROS_CPU_MCAUSE_TIMER                 (0x8000000000000007)
#define PHAROS_CPU_MCAUSE_EXT                   (0x800000000000000B)
#define PHAROS_CPU_MCAUSE_SOFT                  (0x8000000000000003)


#define PHAROS_CPU_CONTEXT_MSTATUS_OFFSET       (0  * 8U)
#define PHAROS_CPU_CONTEXT_SATP_OFFSET          (1U * 8U)
#define PHAROS_CPU_CONTEXT_RA_OFFSET            (2U * 8U)
#define PHAROS_CPU_CONTEXT_SP_OFFSET            (3U * 8U)
#define PHAROS_CPU_CONTEXT_T0_OFFSET            (4U * 8U)
#define PHAROS_CPU_CONTEXT_T1_OFFSET            (5U * 8U)
#define PHAROS_CPU_CONTEXT_T2_OFFSET            (6U * 8U)
#define PHAROS_CPU_CONTEXT_T3_OFFSET            (7U * 8U)
#define PHAROS_CPU_CONTEXT_T4_OFFSET            (8U * 8U)
#define PHAROS_CPU_CONTEXT_T5_OFFSET            (9U * 8U)
#define PHAROS_CPU_CONTEXT_T6_OFFSET            (10U * 8U)
#define PHAROS_CPU_CONTEXT_S0_OFFSET            (11U * 8U)
#define PHAROS_CPU_CONTEXT_S1_OFFSET            (12U * 8U)
#define PHAROS_CPU_CONTEXT_S2_OFFSET            (13U * 8U)
#define PHAROS_CPU_CONTEXT_S3_OFFSET            (14U * 8U)
#define PHAROS_CPU_CONTEXT_S4_OFFSET            (15U * 8U)
#define PHAROS_CPU_CONTEXT_S5_OFFSET            (16U * 8U)
#define PHAROS_CPU_CONTEXT_S6_OFFSET            (17U * 8U)
#define PHAROS_CPU_CONTEXT_S7_OFFSET            (18U * 8U)
#define PHAROS_CPU_CONTEXT_S8_OFFSET            (19U * 8U)
#define PHAROS_CPU_CONTEXT_S9_OFFSET            (20U * 8U)
#define PHAROS_CPU_CONTEXT_S10_OFFSET           (21U * 8U)
#define PHAROS_CPU_CONTEXT_S11_OFFSET           (22U * 8U)

#define PHAROS_CPU_TCB_IRQ_RA_OFFSET            (PHAROS_CPU_CONTEXT_S11_OFFSET + 1U * 8U)
#define PHAROS_CPU_TCB_IRQ_SP_OFFSET            (PHAROS_CPU_CONTEXT_S11_OFFSET + 2U * 8U)
#define PHAROS_CPU_TCB_IRQ_GP_OFFSET            (PHAROS_CPU_CONTEXT_S11_OFFSET + 3U * 8U)
#define PHAROS_CPU_TCB_IRQ_TP_OFFSET            (PHAROS_CPU_CONTEXT_S11_OFFSET + 4U * 8U)
#define PHAROS_CPU_TCB_IRQ_T0_OFFSET            (PHAROS_CPU_CONTEXT_S11_OFFSET + 5U * 8U)
#define PHAROS_CPU_TCB_IRQ_T1_OFFSET            (PHAROS_CPU_CONTEXT_S11_OFFSET + 6U * 8U)
#define PHAROS_CPU_TCB_IRQ_T2_OFFSET            (PHAROS_CPU_CONTEXT_S11_OFFSET + 7U * 8U)
#define PHAROS_CPU_TCB_IRQ_S0_OFFSET            (PHAROS_CPU_CONTEXT_S11_OFFSET + 8U * 8U)
#define PHAROS_CPU_TCB_IRQ_S1_OFFSET            (PHAROS_CPU_CONTEXT_S11_OFFSET + 9U * 8U)
#define PHAROS_CPU_TCB_IRQ_A0_OFFSET            (PHAROS_CPU_CONTEXT_S11_OFFSET + 10U * 8U)
#define PHAROS_CPU_TCB_IRQ_A1_OFFSET            (PHAROS_CPU_CONTEXT_S11_OFFSET + 11U * 8U)
#define PHAROS_CPU_TCB_IRQ_A2_OFFSET            (PHAROS_CPU_CONTEXT_S11_OFFSET + 12U * 8U)
#define PHAROS_CPU_TCB_IRQ_A3_OFFSET            (PHAROS_CPU_CONTEXT_S11_OFFSET + 13U * 8U)
#define PHAROS_CPU_TCB_IRQ_A4_OFFSET            (PHAROS_CPU_CONTEXT_S11_OFFSET + 14U * 8U)
#define PHAROS_CPU_TCB_IRQ_A5_OFFSET            (PHAROS_CPU_CONTEXT_S11_OFFSET + 15U * 8U)
#define PHAROS_CPU_TCB_IRQ_A6_OFFSET            (PHAROS_CPU_CONTEXT_S11_OFFSET + 16U * 8U)
#define PHAROS_CPU_TCB_IRQ_A7_OFFSET            (PHAROS_CPU_CONTEXT_S11_OFFSET + 17U * 8U)
#define PHAROS_CPU_TCB_IRQ_S2_OFFSET            (PHAROS_CPU_CONTEXT_S11_OFFSET + 18U * 8U)
#define PHAROS_CPU_TCB_IRQ_S3_OFFSET            (PHAROS_CPU_CONTEXT_S11_OFFSET + 19U * 8U)
#define PHAROS_CPU_TCB_IRQ_S4_OFFSET            (PHAROS_CPU_CONTEXT_S11_OFFSET + 20U * 8U)
#define PHAROS_CPU_TCB_IRQ_S5_OFFSET            (PHAROS_CPU_CONTEXT_S11_OFFSET + 21U * 8U)
#define PHAROS_CPU_TCB_IRQ_S6_OFFSET            (PHAROS_CPU_CONTEXT_S11_OFFSET + 22U * 8U)
#define PHAROS_CPU_TCB_IRQ_S7_OFFSET            (PHAROS_CPU_CONTEXT_S11_OFFSET + 23U * 8U)
#define PHAROS_CPU_TCB_IRQ_S8_OFFSET            (PHAROS_CPU_CONTEXT_S11_OFFSET + 24U * 8U)
#define PHAROS_CPU_TCB_IRQ_S9_OFFSET            (PHAROS_CPU_CONTEXT_S11_OFFSET + 25U * 8U)
#define PHAROS_CPU_TCB_IRQ_S10_OFFSET           (PHAROS_CPU_CONTEXT_S11_OFFSET + 26U * 8U)
#define PHAROS_CPU_TCB_IRQ_S11_OFFSET           (PHAROS_CPU_CONTEXT_S11_OFFSET + 27U * 8U)
#define PHAROS_CPU_TCB_IRQ_T3_OFFSET            (PHAROS_CPU_CONTEXT_S11_OFFSET + 28U * 8U)
#define PHAROS_CPU_TCB_IRQ_T4_OFFSET            (PHAROS_CPU_CONTEXT_S11_OFFSET + 29U * 8U)
#define PHAROS_CPU_TCB_IRQ_T5_OFFSET            (PHAROS_CPU_CONTEXT_S11_OFFSET + 30U * 8U)
#define PHAROS_CPU_TCB_IRQ_T6_OFFSET            (PHAROS_CPU_CONTEXT_S11_OFFSET + 31U * 8U)
#define PHAROS_CPU_TCB_IRQ_MEPC_OFFSET          (PHAROS_CPU_CONTEXT_S11_OFFSET + 32U * 8U)
#define PHAROS_CPU_TCB_IRQ_MSTATUS_OFFSET       (PHAROS_CPU_CONTEXT_S11_OFFSET + 33U * 8U)
#define PHAROS_CPU_TCB_IRQ_FPU_OFFSET           (PHAROS_CPU_CONTEXT_S11_OFFSET + 34U * 8U)
#define PHAROS_CPU_TCB_IRQ_F0_OFFSET            (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 0   * 8U)
#define PHAROS_CPU_TCB_IRQ_F1_OFFSET            (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 1U  * 8U)
#define PHAROS_CPU_TCB_IRQ_F2_OFFSET            (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 2U  * 8U)
#define PHAROS_CPU_TCB_IRQ_F3_OFFSET            (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 3U  * 8U)
#define PHAROS_CPU_TCB_IRQ_F4_OFFSET            (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 4U  * 8U)
#define PHAROS_CPU_TCB_IRQ_F5_OFFSET            (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 5U  * 8U)
#define PHAROS_CPU_TCB_IRQ_F6_OFFSET            (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 6U  * 8U)
#define PHAROS_CPU_TCB_IRQ_F7_OFFSET            (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 7U  * 8U)
#define PHAROS_CPU_TCB_IRQ_F8_OFFSET            (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 8U  * 8U)
#define PHAROS_CPU_TCB_IRQ_F9_OFFSET            (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 9U  * 8U)
#define PHAROS_CPU_TCB_IRQ_F10_OFFSET           (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 10U * 8U)
#define PHAROS_CPU_TCB_IRQ_F11_OFFSET           (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 11U * 8U)
#define PHAROS_CPU_TCB_IRQ_F12_OFFSET           (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 12U * 8U)
#define PHAROS_CPU_TCB_IRQ_F13_OFFSET           (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 13U * 8U)
#define PHAROS_CPU_TCB_IRQ_F14_OFFSET           (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 14U * 8U)
#define PHAROS_CPU_TCB_IRQ_F15_OFFSET           (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 15U * 8U)
#define PHAROS_CPU_TCB_IRQ_F16_OFFSET           (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 16U * 8U)
#define PHAROS_CPU_TCB_IRQ_F17_OFFSET           (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 17U * 8U)
#define PHAROS_CPU_TCB_IRQ_F18_OFFSET           (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 18U * 8U)
#define PHAROS_CPU_TCB_IRQ_F19_OFFSET           (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 19U * 8U)
#define PHAROS_CPU_TCB_IRQ_F20_OFFSET           (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 20U * 8U)
#define PHAROS_CPU_TCB_IRQ_F21_OFFSET           (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 21U * 8U)
#define PHAROS_CPU_TCB_IRQ_F22_OFFSET           (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 22U * 8U)
#define PHAROS_CPU_TCB_IRQ_F23_OFFSET           (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 23U * 8U)
#define PHAROS_CPU_TCB_IRQ_F24_OFFSET           (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 24U * 8U)
#define PHAROS_CPU_TCB_IRQ_F25_OFFSET           (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 25U * 8U)
#define PHAROS_CPU_TCB_IRQ_F26_OFFSET           (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 26U * 8U)
#define PHAROS_CPU_TCB_IRQ_F27_OFFSET           (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 27U * 8U)
#define PHAROS_CPU_TCB_IRQ_F28_OFFSET           (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 28U * 8U)
#define PHAROS_CPU_TCB_IRQ_F29_OFFSET           (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 29U * 8U)
#define PHAROS_CPU_TCB_IRQ_F30_OFFSET           (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 30U * 8U)
#define PHAROS_CPU_TCB_IRQ_F31_OFFSET           (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 31U * 8U)
#define PHAROS_CPU_TCB_IRQ_FCSR_OFFSET          (PHAROS_CPU_TCB_IRQ_FPU_OFFSET + 32U * 8U)


#define PHAROS_CPU_OFFSET_ENTRY_POINT           (PHAROS_CPU_TCB_IRQ_FCSR_OFFSET  + 1U * 8U)
#define PHAROS_CPU_OFFSET_USER_STACK            (PHAROS_CPU_OFFSET_ENTRY_POINT + 1U * 8U)
#define PHAROS_CPU_OFFSET_USER_STACK_CURRENT    (PHAROS_CPU_OFFSET_USER_STACK + 1U * 8U)
#define PHAROS_CPU_OFFSET_KERNEL_STACK          (PHAROS_CPU_OFFSET_USER_STACK_CURRENT  + 1U * 8U)

#define PHAROS_CPU_CONTEXT_RA_IPC               (PHAROS_CPU_OFFSET_KERNEL_STACK + 1U * 8U)

#define PHAROS_CPU_CONTEXT_FPU_START            (PHAROS_CPU_CONTEXT_RA_IPC + 1U * 8U)
#define PHAROS_CPU_CONTEXT_F0_OFFSET            (PHAROS_CPU_CONTEXT_FPU_START + 0 * 8U)
#define PHAROS_CPU_CONTEXT_F1_OFFSET            (PHAROS_CPU_CONTEXT_FPU_START + 1U * 8U)
#define PHAROS_CPU_CONTEXT_F2_OFFSET            (PHAROS_CPU_CONTEXT_FPU_START + 2U * 8U)
#define PHAROS_CPU_CONTEXT_F3_OFFSET            (PHAROS_CPU_CONTEXT_FPU_START + 3U * 8U)
#define PHAROS_CPU_CONTEXT_F4_OFFSET            (PHAROS_CPU_CONTEXT_FPU_START + 4U * 8U)
#define PHAROS_CPU_CONTEXT_F5_OFFSET            (PHAROS_CPU_CONTEXT_FPU_START + 5U * 8U)
#define PHAROS_CPU_CONTEXT_F6_OFFSET            (PHAROS_CPU_CONTEXT_FPU_START + 6U * 8U)
#define PHAROS_CPU_CONTEXT_F7_OFFSET            (PHAROS_CPU_CONTEXT_FPU_START + 7U * 8U)
#define PHAROS_CPU_CONTEXT_F8_OFFSET            (PHAROS_CPU_CONTEXT_FPU_START + 8U * 8U)
#define PHAROS_CPU_CONTEXT_F9_OFFSET            (PHAROS_CPU_CONTEXT_FPU_START + 9U * 8U)
#define PHAROS_CPU_CONTEXT_F10_OFFSET           (PHAROS_CPU_CONTEXT_FPU_START + 10U * 8U)
#define PHAROS_CPU_CONTEXT_F11_OFFSET           (PHAROS_CPU_CONTEXT_FPU_START + 11U * 8U)
#define PHAROS_CPU_CONTEXT_F12_OFFSET           (PHAROS_CPU_CONTEXT_FPU_START + 12U * 8U)
#define PHAROS_CPU_CONTEXT_F13_OFFSET           (PHAROS_CPU_CONTEXT_FPU_START + 13U * 8U)
#define PHAROS_CPU_CONTEXT_F14_OFFSET           (PHAROS_CPU_CONTEXT_FPU_START + 14U * 8U)
#define PHAROS_CPU_CONTEXT_F15_OFFSET           (PHAROS_CPU_CONTEXT_FPU_START + 15U * 8U)
#define PHAROS_CPU_CONTEXT_F16_OFFSET           (PHAROS_CPU_CONTEXT_FPU_START + 16U * 8U)
#define PHAROS_CPU_CONTEXT_F17_OFFSET           (PHAROS_CPU_CONTEXT_FPU_START + 17U * 8U)
#define PHAROS_CPU_CONTEXT_F18_OFFSET           (PHAROS_CPU_CONTEXT_FPU_START + 18U * 8U)
#define PHAROS_CPU_CONTEXT_F19_OFFSET           (PHAROS_CPU_CONTEXT_FPU_START + 19U * 8U)
#define PHAROS_CPU_CONTEXT_F20_OFFSET           (PHAROS_CPU_CONTEXT_FPU_START + 20U * 8U)
#define PHAROS_CPU_CONTEXT_F21_OFFSET           (PHAROS_CPU_CONTEXT_FPU_START + 21U * 8U)
#define PHAROS_CPU_CONTEXT_F22_OFFSET           (PHAROS_CPU_CONTEXT_FPU_START + 22U * 8U)
#define PHAROS_CPU_CONTEXT_F23_OFFSET           (PHAROS_CPU_CONTEXT_FPU_START + 23U * 8U)
#define PHAROS_CPU_CONTEXT_F24_OFFSET           (PHAROS_CPU_CONTEXT_FPU_START + 24U * 8U)
#define PHAROS_CPU_CONTEXT_F25_OFFSET           (PHAROS_CPU_CONTEXT_FPU_START + 25U * 8U)
#define PHAROS_CPU_CONTEXT_F26_OFFSET           (PHAROS_CPU_CONTEXT_FPU_START + 26U * 8U)
#define PHAROS_CPU_CONTEXT_F27_OFFSET           (PHAROS_CPU_CONTEXT_FPU_START + 27U * 8U)
#define PHAROS_CPU_CONTEXT_F28_OFFSET           (PHAROS_CPU_CONTEXT_FPU_START + 28U * 8U)
#define PHAROS_CPU_CONTEXT_F29_OFFSET           (PHAROS_CPU_CONTEXT_FPU_START + 29U * 8U)
#define PHAROS_CPU_CONTEXT_F30_OFFSET           (PHAROS_CPU_CONTEXT_FPU_START + 30U * 8U)
#define PHAROS_CPU_CONTEXT_F31_OFFSET           (PHAROS_CPU_CONTEXT_FPU_START + 31U * 8U)
#define PHAROS_CPU_CONTEXT_FCSR_OFFSET          (PHAROS_CPU_CONTEXT_FPU_START + 32U * 8U)

#define PHAROS_CPU_CONTEXT_DIRECT_IO_OFFSET     (PHAROS_CPU_CONTEXT_FCSR_OFFSET + 1U * 8U)
#define PHAROS_CPU_CONTEXT_DIRECT_IO_RA_OFFSET  (PHAROS_CPU_CONTEXT_DIRECT_IO_OFFSET + 3U * 4U )

#define PHAROS_CPU_EXCEPTION_ENV_CALL_U         (8U)
#define PHAROS_CPU_EXCEPTION_ENV_CALL_M         (11U)

#define PHAROS_CORE_TABLE_RUNNING_THREAD_OFFSET     (0)
#define PHAROS_CORE_TABLE_DISPATCH_LEVEL_OFFSET     (PHAROS_CORE_TABLE_RUNNING_THREAD_OFFSET + __SIZEOF_POINTER__)
#define PHAROS_CORE_TABLE_INTERRUPT_LEVEL_OFFSET    (PHAROS_CORE_TABLE_DISPATCH_LEVEL_OFFSET + __SIZEOF_POINTER__)
#define PHAROS_CORE_TABLE_CONTEXT_NEEDED_OFFSET     (PHAROS_CORE_TABLE_INTERRUPT_LEVEL_OFFSET + __SIZEOF_POINTER__)


/* PHAROS_RISC64_ASM_H */
#endif	
