/****************************************************************************
 * Pharos - A Real-Time Secure Operating System                             *
 * Copyright 2020 Pedro Macara and Filipe Monteiro                          *
 *                                                                          *
 * Licensed under the Apache License, Version 2.0 (the "License");          *
 * you may not use this file except in compliance with the License.         *
 * You may obtain a copy of the License at                                  *
 *                                                                          *
 *     http://www.apache.org/licenses/LICENSE-2.0                           *
 *                                                                          *
 * Unless required by applicable law or agreed to in writing, software      *
 * distributed under the License is distributed on an "AS IS" BASIS,        *
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. *
 * See the License for the specific language governing permissions and      *
 * limitations under the License.                                           *
 *                                                                          *
 ****************************************************************************/


#include <pharos/hal/hal.h>
#include <pharos/hal/cpu/sections.h>
#include <pharos/hal/cpu/linker.h>


RONLY_SECTION const uint8_t *pharosVPartitionsStart[] = {
    &partition0Start ,
    &partition1Start ,
    &partition2Start ,
    &partition3Start ,
    &partition4Start ,
    &partition5Start ,
    &partition6Start ,
    &partition7Start ,
    &partition8Start ,
    &partition9Start ,
    &partition10Start ,
    &partition11Start ,
    &partition12Start ,
    &partition13Start ,
    &partition14Start ,
    &partition15Start ,
    &partition16Start ,
    &partition17Start ,
    &partition18Start ,
    &partition19Start ,
    &partition20Start ,
    &partition21Start ,
    &partition22Start ,
    &partition23Start ,
    &partition24Start ,
    &partition25Start ,
    &partition26Start ,
    &partition27Start ,
    &partition28Start ,
    &partition29Start ,
    &partition30Start ,
    &partition31Start ,
    &partition32Start ,
    &partition33Start ,
    &partition34Start ,
    &partition35Start ,
    &partition36Start ,
    &partition37Start ,
    &partition38Start ,
    &partition39Start ,
    &partition40Start ,
    &partition41Start ,
    &partition42Start ,
    &partition43Start ,
    &partition44Start ,
    &partition45Start ,
    &partition46Start ,
    &partition47Start ,
    &partition48Start ,
    &partition49Start ,
    &partition50Start ,
    &partition51Start ,
    &partition52Start ,
    &partition53Start ,
    &partition54Start ,
    &partition55Start ,
    &partition56Start ,
    &partition57Start ,
    &partition58Start ,
    &partition59Start ,
    &partition60Start ,
    &partition61Start ,
    &partition62Start ,
    &partition63Start ,
};

RONLY_SECTION const uint8_t *pharosVPartitionsEnd[] = {
    &partition0End ,
    &partition1End ,
    &partition2End ,
    &partition3End ,
    &partition4End ,
    &partition5End ,
    &partition6End ,
    &partition7End ,
    &partition8End ,
    &partition9End ,
    &partition10End ,
    &partition11End ,
    &partition12End ,
    &partition13End ,
    &partition14End ,
    &partition15End ,
    &partition16End ,
    &partition17End ,
    &partition18End ,
    &partition19End ,
    &partition20End ,
    &partition21End ,
    &partition22End ,
    &partition23End ,
    &partition24End ,
    &partition25End ,
    &partition26End ,
    &partition27End ,
    &partition28End ,
    &partition29End ,
    &partition30End ,
    &partition31End ,
    &partition32End ,
    &partition33End ,
    &partition34End ,
    &partition35End ,
    &partition36End ,
    &partition37End ,
    &partition38End ,
    &partition39End ,
    &partition40End ,
    &partition41End ,
    &partition42End ,
    &partition43End ,
    &partition44End ,
    &partition45End ,
    &partition46End ,
    &partition47End ,
    &partition48End ,
    &partition49End ,
    &partition50End ,
    &partition51End ,
    &partition52End ,
    &partition53End ,
    &partition54End ,
    &partition55End ,
    &partition56End ,
    &partition57End ,
    &partition58End ,
    &partition59End ,
    &partition60End ,
    &partition61End ,
    &partition62End ,
    &partition63End ,
};
