/****************************************************************************
 * Pharos - A Real-Time Secure Operating System                             *
 * Copyright 2020 Pedro Macara and Filipe Monteiro                          *
 *                                                                          *
 * Licensed under the Apache License, Version 2.0 (the "License");          *
 * you may not use this file except in compliance with the License.         *
 * You may obtain a copy of the License at                                  *
 *                                                                          *
 *     http://www.apache.org/licenses/LICENSE-2.0                           *
 *                                                                          *
 * Unless required by applicable law or agreed to in writing, software      *
 * distributed under the License is distributed on an "AS IS" BASIS,        *
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. *
 * See the License for the specific language governing permissions and      *
 * limitations under the License.                                           *
 *                                                                          *
 ****************************************************************************/


#include <pharos/kernel/object/declarations.h>
#include <pharos/kernel/object/protection.h>
#include <pharos/hal/boardApi.h>
#include <pharos/hal/cpu/linker.h>
#include <pharos/kernel/interrupt/interrupt.h>
#include <pharos/kernel/partition/partition.h>
#include <pharos/kernel/core/coreconfinline.h>
#include <pharos/kernel/core/coreinlines.h>
#include <pharos/hal/cpu/sections.h>




RONLY_SECTION const uint64_t *partitionsBssStart[] = {
    &partition0BssStart ,
    &partition1BssStart ,
    &partition2BssStart ,
    &partition3BssStart ,
    &partition4BssStart ,
    &partition5BssStart ,
    &partition6BssStart ,
    &partition7BssStart ,
    &partition8BssStart ,
    &partition9BssStart ,
    &partition10BssStart ,
    &partition11BssStart ,
    &partition12BssStart ,
    &partition13BssStart ,
    &partition14BssStart ,
    &partition15BssStart ,
    &partition16BssStart ,
    &partition17BssStart ,
    &partition18BssStart ,
    &partition19BssStart ,
    &partition20BssStart ,
    &partition21BssStart ,
    &partition22BssStart ,
    &partition23BssStart ,
    &partition24BssStart ,
    &partition25BssStart ,
    &partition26BssStart ,
    &partition27BssStart ,
    &partition28BssStart ,
    &partition29BssStart ,
    &partition30BssStart ,
    &partition31BssStart ,
    &partition32BssStart ,
    &partition33BssStart ,
    &partition34BssStart ,
    &partition35BssStart ,
    &partition36BssStart ,
    &partition37BssStart ,
    &partition38BssStart ,
    &partition39BssStart ,
    &partition40BssStart ,
    &partition41BssStart ,
    &partition42BssStart ,
    &partition43BssStart ,
    &partition44BssStart ,
    &partition45BssStart ,
    &partition46BssStart ,
    &partition47BssStart ,
    &partition48BssStart ,
    &partition49BssStart ,
    &partition50BssStart ,
    &partition51BssStart ,
    &partition52BssStart ,
    &partition53BssStart ,
    &partition54BssStart ,
    &partition55BssStart ,
    &partition56BssStart ,
    &partition57BssStart ,
    &partition58BssStart ,
    &partition59BssStart ,
    &partition60BssStart ,
    &partition61BssStart ,
    &partition62BssStart ,
    &partition63BssStart ,
};

RONLY_SECTION const uint64_t *partitionsDataStart[] = {
    &partition0DataStart ,
    &partition1DataStart ,
    &partition2DataStart ,
    &partition3DataStart ,
    &partition4DataStart ,
    &partition5DataStart ,
    &partition6DataStart ,
    &partition7DataStart ,
    &partition8DataStart ,
    &partition9DataStart ,
    &partition10DataStart ,
    &partition11DataStart ,
    &partition12DataStart ,
    &partition13DataStart ,
    &partition14DataStart ,
    &partition15DataStart ,
    &partition16DataStart ,
    &partition17DataStart ,
    &partition18DataStart ,
    &partition19DataStart ,
    &partition20DataStart ,
    &partition21DataStart ,
    &partition22DataStart ,
    &partition23DataStart ,
    &partition24DataStart ,
    &partition25DataStart ,
    &partition26DataStart ,
    &partition27DataStart ,
    &partition28DataStart ,
    &partition29DataStart ,
    &partition30DataStart ,
    &partition31DataStart ,
    &partition32DataStart ,
    &partition33DataStart ,
    &partition34DataStart ,
    &partition35DataStart ,
    &partition36DataStart ,
    &partition37DataStart ,
    &partition38DataStart ,
    &partition39DataStart ,
    &partition40DataStart ,
    &partition41DataStart ,
    &partition42DataStart ,
    &partition43DataStart ,
    &partition44DataStart ,
    &partition45DataStart ,
    &partition46DataStart ,
    &partition47DataStart ,
    &partition48DataStart ,
    &partition49DataStart ,
    &partition50DataStart ,
    &partition51DataStart ,
    &partition52DataStart ,
    &partition53DataStart ,
    &partition54DataStart ,
    &partition55DataStart ,
    &partition56DataStart ,
    &partition57DataStart ,
    &partition58DataStart ,
    &partition59DataStart ,
    &partition60DataStart ,
    &partition61DataStart ,
    &partition62DataStart ,
    &partition63DataStart ,
};


RONLY_SECTION const uint64_t *partitionsDataAddr[] = {
    &pharosPartition0DataAddr ,
    &pharosPartition1DataAddr ,
    &pharosPartition2DataAddr ,
    &pharosPartition3DataAddr ,
    &pharosPartition4DataAddr ,
    &pharosPartition5DataAddr ,
    &pharosPartition6DataAddr ,
    &pharosPartition7DataAddr ,
    &pharosPartition8DataAddr ,
    &pharosPartition9DataAddr ,
    &pharosPartition10DataAddr ,
    &pharosPartition11DataAddr ,
    &pharosPartition12DataAddr ,
    &pharosPartition13DataAddr ,
    &pharosPartition14DataAddr ,
    &pharosPartition15DataAddr ,
    &pharosPartition16DataAddr ,
    &pharosPartition17DataAddr ,
    &pharosPartition18DataAddr ,
    &pharosPartition19DataAddr ,
    &pharosPartition20DataAddr ,
    &pharosPartition21DataAddr ,
    &pharosPartition22DataAddr ,
    &pharosPartition23DataAddr ,
    &pharosPartition24DataAddr ,
    &pharosPartition25DataAddr ,
    &pharosPartition26DataAddr ,
    &pharosPartition27DataAddr ,
    &pharosPartition28DataAddr ,
    &pharosPartition29DataAddr ,
    &pharosPartition30DataAddr ,
    &pharosPartition31DataAddr ,
    &pharosPartition32DataAddr ,
    &pharosPartition33DataAddr ,
    &pharosPartition34DataAddr ,
    &pharosPartition35DataAddr ,
    &pharosPartition36DataAddr ,
    &pharosPartition37DataAddr ,
    &pharosPartition38DataAddr ,
    &pharosPartition39DataAddr ,
    &pharosPartition40DataAddr ,
    &pharosPartition41DataAddr ,
    &pharosPartition42DataAddr ,
    &pharosPartition43DataAddr ,
    &pharosPartition44DataAddr ,
    &pharosPartition45DataAddr ,
    &pharosPartition46DataAddr ,
    &pharosPartition47DataAddr ,
    &pharosPartition48DataAddr ,
    &pharosPartition49DataAddr ,
    &pharosPartition50DataAddr ,
    &pharosPartition51DataAddr ,
    &pharosPartition52DataAddr ,
    &pharosPartition53DataAddr ,
    &pharosPartition54DataAddr ,
    &pharosPartition55DataAddr ,
    &pharosPartition56DataAddr ,
    &pharosPartition57DataAddr ,
    &pharosPartition58DataAddr ,
    &pharosPartition59DataAddr ,
    &pharosPartition60DataAddr ,
    &pharosPartition61DataAddr ,
    &pharosPartition62DataAddr ,
    &pharosPartition63DataAddr ,
};
